package com.urzednicza.youtuberemotebackend.enums;

public enum MessageType {
    ERROR, START, STOP, MEDIA_CONTROL, SET_RECEIVER, RECEIVERS, CONTROLS_SONG, CONTROLS_TIME, CONTROLS_DETAILS,
    CURRENT_RECEIVER, QUEUE, HEART_BEAT, QUEUE_CONTROL, HOME
}
