package com.example.youtuberemoteandroid.enums;

public enum MessageType {
    CONTROLS_TIME,CONTROLS_SONG,CONTROLS_DETAILS,QUEUE,QUEUE_LENGTH,HEART_BEAT,START,
    MEDIA_CONTROL,QUEUE_CONTROL,ERROR,HOME,RECEIVERS,CURRENT_RECEIVER
}
